{{- if .Values.plugin.enabled }}
apiVersion: catalog.cattle.io/v1
kind: UIPlugin
metadata:
  name: {{ include "plugin-worker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ (include "plugin-worker.labels" . | nindent 4) }}
spec:
  plugin:
    name: {{ include "plugin-worker.fullname" . }}
    version: {{ (semver (default .Chart.AppVersion .Values.plugin.versionOverride)).Original }}
    endpoint: http://{{ include "plugin-server.fullname" . }}.{{ .Release.Namespace }}.svc
    noCache: {{ .Values.plugin.noCache }}
{{- end }}
