# Default values for sample.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  noCache: false
